// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6xqWeMEn-U2hr483nJUiAzsI-f_VtZfg',
    appId: '1:622996882555:web:26d27fc1b127b8e8fa0ede',
    messagingSenderId: '622996882555',
    projectId: 'cricfieldanlyzer',
    authDomain: 'cricfieldanlyzer.firebaseapp.com',
    storageBucket: 'cricfieldanlyzer.firebasestorage.app',
    measurementId: 'G-PDV31V2MXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOKz4zO1VUWco9QG61yKM1E8ZspjAMYJ0',
    appId: '1:622996882555:android:cb48b9b1dbcb9acbfa0ede',
    messagingSenderId: '622996882555',
    projectId: 'cricfieldanlyzer',
    storageBucket: 'cricfieldanlyzer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADxWCF8zVpotLCkeIbCrwYfNqP4vNkqik',
    appId: '1:622996882555:ios:458c7883f788e6bafa0ede',
    messagingSenderId: '622996882555',
    projectId: 'cricfieldanlyzer',
    storageBucket: 'cricfieldanlyzer.firebasestorage.app',
    iosBundleId: 'com.example.cricFieldProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADxWCF8zVpotLCkeIbCrwYfNqP4vNkqik',
    appId: '1:622996882555:ios:458c7883f788e6bafa0ede',
    messagingSenderId: '622996882555',
    projectId: 'cricfieldanlyzer',
    storageBucket: 'cricfieldanlyzer.firebasestorage.app',
    iosBundleId: 'com.example.cricFieldProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6xqWeMEn-U2hr483nJUiAzsI-f_VtZfg',
    appId: '1:622996882555:web:3f29c3deab3b10cafa0ede',
    messagingSenderId: '622996882555',
    projectId: 'cricfieldanlyzer',
    authDomain: 'cricfieldanlyzer.firebaseapp.com',
    storageBucket: 'cricfieldanlyzer.firebasestorage.app',
    measurementId: 'G-DMHNTFWRPP',
  );

}